// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CTRLS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of ap_return
//        bit 31~0 - ap_return[31:0] (Read)
// 0x18 : Data signal of Thu
//        bit 31~0 - Thu[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of Ind
//        bit 31~0 - Ind[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of Mid
//        bit 31~0 - Mid[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of Rin
//        bit 31~0 - Rin[31:0] (Read/Write)
// 0x34 : reserved
// 0x38 : Data signal of Lit
//        bit 31~0 - Lit[31:0] (Read/Write)
// 0x3c : reserved
// 0x40 : Data signal of ACC_X
//        bit 31~0 - ACC_X[31:0] (Read/Write)
// 0x44 : reserved
// 0x48 : Data signal of ACC_Y
//        bit 31~0 - ACC_Y[31:0] (Read/Write)
// 0x4c : reserved
// 0x50 : Data signal of ACC_Z
//        bit 31~0 - ACC_Z[31:0] (Read/Write)
// 0x54 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XBPNN_CTRLS_ADDR_AP_CTRL    0x00
#define XBPNN_CTRLS_ADDR_GIE        0x04
#define XBPNN_CTRLS_ADDR_IER        0x08
#define XBPNN_CTRLS_ADDR_ISR        0x0c
#define XBPNN_CTRLS_ADDR_AP_RETURN  0x10
#define XBPNN_CTRLS_BITS_AP_RETURN  32
#define XBPNN_CTRLS_ADDR_THU_DATA   0x18
#define XBPNN_CTRLS_BITS_THU_DATA   32
#define XBPNN_CTRLS_ADDR_IND_DATA   0x20
#define XBPNN_CTRLS_BITS_IND_DATA   32
#define XBPNN_CTRLS_ADDR_MID_DATA   0x28
#define XBPNN_CTRLS_BITS_MID_DATA   32
#define XBPNN_CTRLS_ADDR_RIN_DATA   0x30
#define XBPNN_CTRLS_BITS_RIN_DATA   32
#define XBPNN_CTRLS_ADDR_LIT_DATA   0x38
#define XBPNN_CTRLS_BITS_LIT_DATA   32
#define XBPNN_CTRLS_ADDR_ACC_X_DATA 0x40
#define XBPNN_CTRLS_BITS_ACC_X_DATA 32
#define XBPNN_CTRLS_ADDR_ACC_Y_DATA 0x48
#define XBPNN_CTRLS_BITS_ACC_Y_DATA 32
#define XBPNN_CTRLS_ADDR_ACC_Z_DATA 0x50
#define XBPNN_CTRLS_BITS_ACC_Z_DATA 32

